services:
  pixobe-api:
    restart: always
    image: pixobe.com/shopify-coloring:${APP_VERSION}
    ports:
      - 3001:3000
    environment:
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - SHOPIFY_APP_URL=${SHOPIFY_APP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SCOPES=${SCOPES}