# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85deee8bd5bf18a344916cd6acd3f9fd"
name = "Pixobe Coloring"
application_url = "https://coloring.pixobe.com/"
embedded = true
handle = "pixobe-coloring"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_purchases_one_time/update", "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,read_translations,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://coloring.pixobe.com/auth/callback",
  "https://coloring.pixobe.com/auth/shopify/callback",
  "https://coloring.pixobe.com/api/auth/callback"
]

[app_proxy]
url = "https://coloring.pixobe.com/api"
subpath = "pixobe-coloring-app"
prefix = "apps"

[pos]
embedded = false

[metafields]
api_version = "2026-01"

[metaobjects.app.settings]
name = "Pixobe Coloring Settings"
display_name_field = "config"
description = "App settings to persists the Pixobe app defaults used by the Pixobe Coloring application."

  [metaobjects.app.settings.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[metaobjects.app.settings.fields.config]
name = "Settings JSON to store Pixobe Product Coloring app level configuration"
type = "json"
description = "Serialized default configuration captured from the settings form."
